### PR TITLE
Create new setting to the change feed

### LINKED ISSUE #164: Option to start the changefeed at current time
**## Problem Statement**
The startFromBeginning option is hard coded today, making it impossible to start the change feed ignoring previous changes

**## Proposed Solution**
Create a new setting to make it possible to start the change feed with the default behaviour of ignoring previous changes

**## Additional context**
https://github.com/microsoft/kafka-connect-cosmosdb/blob/bf072b6032248a6ed1101e9ce0a67304f65cb768/src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java#L147

### PR DESCRIPTION
**Pull request by marcelopio**
## Type of PR

- [x] Documentation changes
- [x] Code changes
- [x] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR
Today the option to start from beginning on the change feed is hard coded to true. A new setting make it possible to set it to false on demand was created

## Issues Closed or Referenced
- Closes #164

### CODE REVIEW

**Comment by ryancrawcour** [comment]
if setting is set to False, where will it start from? from current datetime and only process future events and ignore the changes up to this point?

**Comment by ryancrawcour** [comment]
The documentation however does say - 


_isStartFromBeginning() | Gets a value indicating whether change feed in the Azure Cosmos DB service **should start from beginning (true) or from current (false)**. 

**By default it's start from current (false)**.This option can be used when: (1) Lease items are not initialized; this setting will be ignored if the lease items exists and have a valid continuation token. (2) Start continuation token option is not specified. (3) Start time option is not specified.
-- | --_


so perhaps we don't need to set these additional properties. 
however, we might want to consider this?

**Comment by ryancrawcour** [comment]
Would also be good to have some tests that test this new functionality. 
I see there is a test that simply ensures the property is set. Although, for unit testing, in this project, it could be argued that this is probably enough (else we're testing Cosmos DB functionality).

So i am ok with not requiring it.

**Comment by marcelopio** [comment]
"By default it's start from current (false)". 

I also tested by just removing the current code that is setting the flag to true, and it started injesting from the point it created the lease container forward. 

I fully agree with more unit tests, it also bothered me, I should have created the pull request as a draft, I was expecting more opinions on the feature than anything else.

I also agree that we should at least support setting the Start time. Will work on that

**Comment by ryancrawcour** [comment]
yeah, we're about to start a new round of dev to address some issues, so will make sure to add better tests. it bothers me too that we have such light testing on this. #sorry

**Comment by ryancrawcour** [comment]
ok, i propose we push this one in as is. start from beginning (true) or current (false) and then open a new issue to add future enhancements for StartTime and StartContinuation

**Comment by ryancrawcour** [comment]
i think the feature is a good add. makes sense. so, thanks for that contribution.

**Pull request merged**
