### PR TITLE
Fixes parsing for empty arrays

### PR DESCRIPTION
**Pull request by javierholguera**
## Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Observability + Testing
- What changes or considerations did you make in relation to observability?

- Did you add testing to account for any new or changed work?

## Issues Closed or Referenced

- Closes #<issue number> (this will automatically close the issue when the PR closes)
- References #<issue number> (this references the issue but does not close with PR)

### CODE REVIEW

**Comment by javierholguera** [comment]
Can anybody have a look at this please? It's a pretty basic bug

**Comment by javierholguera** [comment]
@kushagraThapar I'm not sure what update you refer to. I'm not updating the Kafka library version (that's part of Kafka Connect anyway). What I'm upgrading is the version for this library, which I think it's fair since I'm fixing a bug.

**Comment by kushagraThapar** [comment]
@javierholguera - I am referring to the version of this library (kafka connect cosmos db). 
The reason we don't want to update the version as part of a bug fix is we are not sure whether we will release a hotfix or minor version. That is decided based on a monthly cycle and the changes we do in that particular month. 
Since next kafka connect cosmos db release is due soon, I will update the version once we are closer to the release. Hope it makes sense, thanks!

**Comment by javierholguera** [comment]
@kushagraThapar done

**Review by kushagraThapar — APPROVED** [review]

**Comment by kushagraThapar** [comment]
@javierholguera thanks again for your contribution, we really appreciate it. 
I will merge this PR and this should get released this week as part of our monthly release.

**Pull request merged**
