### PR TITLE
Making Config properties adhere to Sink or source connectors

### LINKED ISSUE #174: Incorrect config properties show up when configuring Sink connector
## Description
When configuring a Sink connector, some configuration properties exposed and shown by Control Center are not related to the Sink connector but are actually properties for a Source connector. This is confusing. 

## Expected Behavior
Only properties related to a Sink connector should show up when configuring a Sink connector.

## Additional Context 
This also applies to a Source connector. Only properties related to a Source connector should show up. 
Ensure that all properties that are meant to have defaults, should show the default
Ensure that all properties that are required have to be set before the connector can be started. 

Note: Some properties are common and shared between the two connector types, these should always show up.

### PR DESCRIPTION
**Pull request by sivamu**
## Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR
- Ensuring that sink config settings only show up when setting up the sink connector (vice versa for source connector)
  - Settings common for both sink and source will show up when setting up either connector
- Some wording changes for setting descriptions
- Minor code style changes

## Issues Closed or Referenced

- Closes #174

### CODE REVIEW

**Comment by sivamu** [comment]
How configs appear for Source:
image

For Sink:
image

**Comment by ryancrawcour** [comment]
> How configs appear for Source:
> image
> 

are all of these config options being used in code?

**Comment by sivamu** [comment]
All the configs are being used except the post-processor, similarly for the sink connector as well. Wasn't sure whether to delete this value since it might be used by kafka-connect or maybe support might be added for it later.

**Comment by ryancrawcour** [comment]
> post-processor

i have a ticket open for removing these, so i'll kill the config at the same time. thanks.

**Review by ryancrawcour — APPROVED** [review]

**Pull request merged**
