### PR TITLE
merging dev to master for new release

### PR DESCRIPTION
**Pull request by ryancrawcour**
## Type of PR

- [ ] Documentation changes
- [ ] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes
- [x] New release

## Purpose of PR
merging latest commits to master for new release

### CODE REVIEW

**Review by sivamu — COMMENTED** [review]
It makes sense to remove the template files in the main version but would it still be useful to leave these files somewhere for reference?

**Comment by ryancrawcour** [comment]
> It makes sense to remove the template files in the main version but would it still be useful to leave these files somewhere for reference?

it might be useful, but those templates were purely internal related templates and with the intention of this repo being made public having 10 different templates when creating a new issue is confusing. 
not sure how to keep them somewhere for reference, perhaps a branch that we keep (like we've done with the scala branch)? 

thoughts?

**Comment by sivamu** [comment]
Right, and now that were won't be any development cycles focused on this project from our end, I don't think they're needed. Not sure about the reference, if we're transferring this to PG, then they might want to add their own templates. This should be fine for now.

**Comment by ryancrawcour** [comment]
yup. that was my thinking too. will let the PG spin up templates that they would like. 
as for references, there's always github commit history to refer to.

**Pull request merged**
