### PR TITLE
Fix parsing of 64 bit values

### LINKED ISSUE #418: INT64 field terminates CosmosDB source connector task while moving data into Kafka
## Description

I have records in CosmosDB with the following property
```
{
    .........................
    "createOnUnixMs": 1637258355246,
     .........................
}
```

I am using the source connector to move the data into a Kafka topic using the following
```
{

     "name": "cosmosdb-source-connector",
      "config": {
                  .........................
                 "key.converter"  : "org.apache.kafka.connect.json.JsonConverter",
                 "key.converter.schemas.enable"  : "false",
                 "value.converter"   : "org.apache.kafka.connect.json.JsonConverter",
                 "value.converter.schemas.enable"   : "false",
                   .........................
     }
}
```

I run into the below error and the connector task fails/terminates. 
```
ERROR WorkerSourceTask{id=cosmosdb-source-connector-1} **Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
connect    | org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "createOnUnixMs",** schema type: INT64
connect    | 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220)
connect    | 	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
connect    | 	at com.azure.cosmos.kafka.connect.source.JsonToStruct.lambda$recordToSchemaAndValue$0(JsonToStruct.java:39)
connect    | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
connect    | 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
connect    | 	at com.azure.cosmos.kafka.connect.source.JsonToStruct.recordToSchemaAndValue(JsonToStruct.java:35)
connect    | 	at com.azure.cosmos.kafka.connect.source.CosmosDBSourceTask.fillRecords(CosmosDBSourceTask.java:186)
connect    | 	at com.azure.cosmos.kafka.connect.source.CosmosDBSourceTask.poll(CosmosDBSourceTask.java:149)
connect    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:291)
connect    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
connect    | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
connect    | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:241)
connect    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect    | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Expected Behavior

- I was hoping the connector would copy the document from CosmosDB to Kafka topic because clearly the value is not null, as being mentioned in the error stack (above)

## Additional Context

Surprisingly,  the sink connector works just fine when moving the record containing the above field (createOnUnixMs) to CosmosDB.

### PR DESCRIPTION
**Pull request by robcam73**
## Type of PR

- [ ] Code changes

## Purpose of PR

Fix bug

## Issues Closed or Referenced

- Closes #418  (this will automatically close the issue when the PR closes)

### CODE REVIEW

**Review by ryancrawcour — APPROVED** [review]

**Comment by ryancrawcour** [comment]
thank you for the contribution @robcam73 !

**Comment by robcam73** [comment]
Sorry, missed this. Would like a new release if possible thanks

**Comment by kushagraThapar** [comment]
@robcam73 - release is in progress - 1.3.1 will be out today. Please check out our release page for updates. https://github.com/microsoft/kafka-connect-cosmosdb/releases

**Comment by robcam73** [comment]
Thanks

**Pull request merged**
