### PR TITLE
Draft of Cosmos ChangeFeed processor

### LINKED ISSUE #4: Must be able to use ChangeFeed to replay data in source
For source (where Cosmos DB is the source), use the ChangeFeed to replay the data

### PR DESCRIPTION
**Pull request by allantargino**
fix #4

### CODE REVIEW

**Comment by ryancrawcour** [comment]
Is the intention of this to implement the Cosmos DB logic that will provide a list of changes to be written to the Kafka topic?

There appears to be a Main class. Is that just for now so that it is runnable and will be removed and replaced with the SourceConnector and SourceTask implementations that @dwhiteddsoft is working on?

**Comment by allantargino** [comment]
Yes, that is the intention. The list of changes is processed by a `ChangeFeedObserver`.
This is just for now, it should be removed in the future.

**Comment by ryancrawcour** [comment]
Main should be removed? And replaced by whatever is implemented in SourceConnector and SourceTask?

**Comment by allantargino** [comment]
Hi @ryancrawcour since I may not push the tests these days, I created issue #32 to track it.

**Comment by ryancrawcour** [comment]
That's fine. Just so we can track it and make sure it gets done.

**Pull request merged**
